-- Nexo ERP v1.1.0 — fluxo integrado de comércio
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null, phone text default '', email text default '',
  notes text default '', created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null, sku text not null, price numeric(14,2) not null check(price>=0),
  cost numeric(14,2) not null default 0 check(cost>=0),
  stock integer not null default 0 check(stock>=0), low_stock_at integer not null default 3,
  active boolean not null default true,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(company_id,sku)
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  order_number bigint generated by default as identity,
  status text not null default 'Pago' check(status in ('Pendente','Pago','Separando','Enviado','Concluído','Cancelado')),
  payment_method text not null default 'PIX',
  total numeric(14,2) not null default 0,
  created_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity integer not null check(quantity>0),
  unit_price numeric(14,2) not null check(unit_price>=0),
  subtotal numeric(14,2) generated always as (quantity*unit_price) stored
);

alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
create policy "members manage customers" on public.customers for all to authenticated
  using(public.is_company_member(company_id)) with check(public.is_company_member(company_id));
create policy "members manage products" on public.products for all to authenticated
  using(public.is_company_member(company_id)) with check(public.is_company_member(company_id));
create policy "members manage orders" on public.orders for all to authenticated
  using(public.is_company_member(company_id)) with check(public.is_company_member(company_id));
create policy "members view order items" on public.order_items for select to authenticated
  using(exists(select 1 from public.orders o where o.id=order_id and public.is_company_member(o.company_id)));

create or replace function public.create_integrated_order(
  requested_company uuid, requested_customer uuid, requested_payment text,
  requested_status text, requested_items jsonb
) returns uuid language plpgsql security definer set search_path=public as $$
declare new_order uuid; line jsonb; product_row public.products%rowtype; total_value numeric(14,2):=0;
begin
  if not public.is_company_member(requested_company) then raise exception 'Acesso negado'; end if;
  if jsonb_array_length(requested_items)=0 then raise exception 'Pedido sem itens'; end if;
  if requested_customer is not null and not exists(
    select 1 from public.customers
    where id=requested_customer and company_id=requested_company
  ) then raise exception 'Cliente inválido'; end if;
  insert into public.orders(company_id,customer_id,payment_method,status,created_by)
  values(requested_company,requested_customer,requested_payment,requested_status,auth.uid()) returning id into new_order;
  for line in select * from jsonb_array_elements(requested_items) loop
    select * into product_row from public.products
      where id=(line->>'product_id')::uuid and company_id=requested_company for update;
    if not found then raise exception 'Produto inválido'; end if;
    if requested_status<>'Pendente' and product_row.stock<(line->>'quantity')::integer then
      raise exception 'Estoque insuficiente para %',product_row.name;
    end if;
    insert into public.order_items(order_id,product_id,quantity,unit_price)
      values(new_order,product_row.id,(line->>'quantity')::integer,product_row.price);
    total_value:=total_value+product_row.price*(line->>'quantity')::integer;
    if requested_status<>'Pendente' then
      update public.products set stock=stock-(line->>'quantity')::integer,updated_at=now() where id=product_row.id;
    end if;
  end loop;
  update public.orders set total=total_value where id=new_order;
  if requested_status<>'Pendente' then
    insert into public.transactions(company_id,description,category,type,amount,transaction_date,status,created_by)
    values(requested_company,'Pedido #'||(select order_number from public.orders where id=new_order),
      'Pedidos','Entrada',total_value,current_date,'Pago',auth.uid());
  end if;
  return new_order;
end $$;
grant execute on function public.create_integrated_order(uuid,uuid,text,text,jsonb) to authenticated;
create index if not exists products_company_idx on public.products(company_id,name);
create index if not exists customers_company_idx on public.customers(company_id,name);
create index if not exists orders_company_date_idx on public.orders(company_id,created_at desc);
