-- Execute no SQL Editor se o schema principal já foi aplicado anteriormente.
create table if not exists public.objectives (id uuid primary key default gen_random_uuid(),title text not null,description text default '',calendar_type text not null check(calendar_type in ('calendar','challenge')),start_date date not null default current_date,total_days integer check(total_days is null or (total_days between 1 and 366)),color text not null default '#7c6cff',created_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.objective_activities (id uuid primary key default gen_random_uuid(),objective_id uuid not null references public.objectives(id) on delete cascade,title text not null,position integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.objective_checkins (id uuid primary key default gen_random_uuid(),objective_id uuid not null references public.objectives(id) on delete cascade,activity_id uuid not null references public.objective_activities(id) on delete cascade,day_key text not null,completed_by uuid not null default auth.uid() references auth.users(id),completed_at timestamptz not null default now(),unique(activity_id,day_key));
alter table public.objectives enable row level security;alter table public.objective_activities enable row level security;alter table public.objective_checkins enable row level security;
create policy "authenticated view objectives" on public.objectives for select to authenticated using(true);create policy "authenticated create objectives" on public.objectives for insert to authenticated with check(created_by=auth.uid());create policy "owners update objectives" on public.objectives for update to authenticated using(created_by=auth.uid()) with check(created_by=auth.uid());create policy "owners delete objectives" on public.objectives for delete to authenticated using(created_by=auth.uid());
create policy "authenticated view objective activities" on public.objective_activities for select to authenticated using(true);
create policy "objective owners create activities" on public.objective_activities for insert to authenticated with check(exists(select 1 from public.objectives o where o.id=objective_id and o.created_by=auth.uid()));
create policy "objective owners update activities" on public.objective_activities for update to authenticated using(exists(select 1 from public.objectives o where o.id=objective_id and o.created_by=auth.uid()));
create policy "objective owners delete activities" on public.objective_activities for delete to authenticated using(exists(select 1 from public.objectives o where o.id=objective_id and o.created_by=auth.uid()));
create policy "authenticated view objective checkins" on public.objective_checkins for select to authenticated using(true);
create policy "authenticated create objective checkins" on public.objective_checkins for insert to authenticated with check(true);
create policy "authenticated delete objective checkins" on public.objective_checkins for delete to authenticated using(true);
create index if not exists objective_activities_objective_idx on public.objective_activities(objective_id,position);create index if not exists objective_checkins_objective_day_idx on public.objective_checkins(objective_id,day_key);
